apiVersion: v1
kind: ConfigMap
metadata:
  name: identityservice-config
  namespace: identityservice
  labels:
    app: identityservice
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "http://+:8080"
  DatabaseProvider: "PostgreSql"
  Jwt__ExpirationTimeHour: "5"
  Jwt__IncreaseExpirationTimeMinutes: "20"
  PATH_BASE: "/api/identity"
  RabbitMq__Host: "${RABBITMQ_HOST}"
  RabbitMq__Port: "${RABBITMQ_PORT}"
