apiVersion: v1
kind: Service
metadata:
  name: identityservice-service
  namespace: identityservice
  labels:
    app: identityservice-api
spec:
  type: LoadBalancer
  selector:
    app: identityservice-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  sessionAffinity: None